### ISSUE TITLE
didnt apper component content 

### ISSUE THREAD

**Issue by omarmok** [pkcwong/react-starter#3]
when i use 
   <Login />

 it work but when i use route didnt work

import React, { Component } from 'react';
import './App.css';
import Navbar from './components/Navbar';
import SignUp from './routes/SignUp';
import Login from './routes/Login';
import { BrowserRouter, Route } from 'react-router-dom';
class App extends Component {
  render() {
    return (
      <BrowserRouter>
      <div>
        <Navbar />
          <Route path="Login" Component={Login} />
          <Route path="SignUp" Component={SignUp} />
      </div>
      </BrowserRouter>
    );
  }
}

export default App;

import React, { Component } from 'react';
class Login extends Component {
  render() {
    return (
     <p>
         login routes
     </p>
    );
  }
}

export default Login;

**Comment by omarmok** [comment]
<img width="602" alt="screen shot 2018-08-31 at 4 03 29 pm" src="https://user-images.githubusercontent.com/21249199/44913969-6db22c80-ad37-11e8-8a3e-9a0af7243f0f.png">

**Comment by omarmok** [comment]
<img width="589" alt="screen shot 2018-08-31 at 4 03 59 pm" src="https://user-images.githubusercontent.com/21249199/44913984-7e62a280-ad37-11e8-9633-e695d9cdd7e7.png">

**Comment by omarmok** [comment]
when i use login as Navbar

**Comment by pkcwong** [comment]
Can you show me your code for ```Navbar```? Also the code for ```App.js``` as the pasted code seems incomplete

**Comment by pkcwong** [comment]
from https://github.com/pkcwong/react-starter/issues/3#issuecomment-417657349 I see that you are using ```Component``` instead of ```component```.

**Comment by omarmok** [comment]
I've discovered this thx

**Comment by pkcwong** [comment]
no problems. feel free to post any enquiries.
